# Defaults: https://github.com/bbatsov/rubocop/blob/master/config/default.yml

AllCops:
  CacheRootDirectory: tmp/.cache
  Exclude:
  - '.git/**/*'
  - 'tmp/**/*'
  - 'bin/**/*'
  - '*.gemspec'
  - 'Gemfile'
  - 'Rakefile'

# Accept both [:a, :b, :c] and %i[a b c]
Style/SymbolArray:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

# Sometimes you absolutely want to be sure you have a boolean.
# The guide for this cop even admits that their recommendation
# doesn't logically equal !!.
Style/DoubleNegation:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/EndOfLine:
  EnforcedStyle: lf

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/FrozenStringLiteralComment:
  Exclude:
  - 'exe/**/*'
  - 'spec/**/*'

# Relax for tests
Metrics/ModuleLength:
  Exclude:
  - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
  - 'spec/**/*'

Metrics/AbcSize:
  Exclude:
  - 'spec/**/*'

Naming/VariableNumber:
  Exclude:
  - 'spec/**/*'

Metrics/ClassLength:
  Exclude:
  - 'spec/**/*'

Style/ClassAndModuleChildren:
  Exclude:
  - 'spec/**/*'